version: '3'
volumes:
  arriba:

services:
  base:
    image: arriba-base
    build: 
      context: ./src
      dockerfile: Dockerfile
  crawl:
    image: arriba-crawl
    build: 
      context: .docker/Crawler
      dockerfile: Dockerfile
    depends_on:
      - base
  crawl-public:
    image: arriba-crawl
    depends_on:
      - crawl
    volumes:
      - arriba:/Arriba/DiskCache
    environment:
      ARRIBA__AZPAT: ${AZPAT}
      ARRIBA__ARRIBATABLE: "Public"
      ARRIBA__itemDatabaseName: "arriba-demo"
      ARRIBA__ITEMPROJECT: "Public"
      ARRIBA__WORKITEMTYPES__0: "Epic"
      ARRIBA__WORKITEMTYPES__1: "Issue"
      ARRIBA__WORKITEMTYPES__1: "Task"
  server:
    build: 
      context: .docker/Server
      dockerfile: Dockerfile
    depends_on:
      - base
    volumes:
      - arriba:/Arriba/DiskCache
    environment:
      ARRIBASERVER__OAUTHCONFIG__APPSECRET: ${APPSECRET}
  web:
    build: 
      context: .docker/WebUI
      dockerfile: Dockerfile
    depends_on:
      - base
    ports:
      - 8080:80
